import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Patient Privacy in the Age of AI: Beyond Basic HIPAA Compliance | Try MedReception',
  description: 'Explore how artificial intelligence is transforming healthcare privacy standards and what patients need to know beyond traditional HIPAA protections in modern medical settings.',
  keywords: 'patient privacy, AI in healthcare, HIPAA compliance, medical data security, healthcare technology, patient rights, artificial intelligence medical records',
  openGraph: {
    title: 'Patient Privacy in the Age of AI: Beyond Basic HIPAA Compliance',
    description: 'Understanding modern healthcare privacy in the era of artificial intelligence and digital medical records.',
    url: 'https://trymedreception.com/blog/patient-privacy-in-the-age-of-ai-beyond-basic-hipaa-complian',
    type: 'article',
    publishedTime: '2024-01-15T09:00:00Z',
  },
}

export default function BlogPost() {
  return (
    <main className="min-h-screen bg-white">
      <section className="bg-gradient-to-br from-[var(--color-dark)] to-[var(--color-primary)] py-20 text-white">
        <div className="max-w-4xl mx-auto px-6">
          <div className="text-sm mb-6 text-white/80">
            <a href="/" className="hover:text-white transition-colors">Home</a>
            <span className="mx-2">›</span>
            <a href="/blog" className="hover:text-white transition-colors">Resources</a>
            <span className="mx-2">›</span>
            <span>Article</span>
          </div>
          
          <div className="text-xs uppercase tracking-widest text-white/70 mb-4 font-medium">
            Patient Education
          </div>
          
          <h1 className="font-cormorant text-5xl md:text-6xl font-light leading-tight max-w-3xl mx-auto text-center mb-8">
            Patient Privacy in the Age of AI: Beyond Basic HIPAA Compliance
          </h1>
          
          <div className="flex items-center justify-center gap-6 text-sm text-white/80">
            <div className="flex items-center gap-2">
              <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5" />
              </svg>
              <span>January 15, 2024</span>
            </div>
            <div className="flex items-center gap-2">
              <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
              <span>8 min read</span>
            </div>
            <div className="flex items-center gap-2">
              <svg className="w-5 h-5" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
              </svg>
              <span>Dr. MedReception Team</span>
            </div>
          </div>
        </div>
      </section>

      <article className="bg-white py-20">
        <div className="max-w-3xl mx-auto px-6">
          <div className="text-[var(--color-ink)] leading-loose text-lg animate-fade-up">
            <p className="text-xl mb-6 font-light">
              You're sitting in your doctor's office when you notice a digital assistant taking notes during your consultation. Later, you receive a treatment recommendation generated by an AI system that analyzed your medical history. These scenarios are no longer science fiction—they're the new reality of modern healthcare. But as artificial intelligence becomes increasingly integrated into medical practice, a critical question emerges: What happens to your most sensitive health information?
            </p>

            <p className="mb-8">
              While HIPAA (Health Insurance Portability and Accountability Act) has protected patient privacy since 1996, the rapid advancement of AI technology has created new vulnerabilities and concerns that existing regulations weren't designed to address. Understanding these evolving privacy challenges isn't just important—it's essential for anyone navigating today's healthcare landscape.
            </p>

            <h2 className="font-cormorant text-4xl text-[var(--color-ink)] mt-16 mb-6 font-light">
              The AI Revolution in Healthcare
            </h2>

            <p className="mb-6">
              Artificial intelligence is transforming healthcare delivery in remarkable ways. Machine learning algorithms can now detect diseases earlier than human practitioners, predict patient outcomes with unprecedented accuracy, and personalize treatment plans based on vast datasets. Virtual health assistants schedule appointments, AI-powered chatbots answer patient questions, and predictive analytics help hospitals allocate resources more efficiently.
            </p>

            <p className="mb-6">
              However, these innovations require something precious: your data. Every symptom you describe, every diagnosis you receive, every medication you take—all of this information feeds into AI systems that promise better healthcare outcomes. The question isn't whether AI will be part of your healthcare future; it's how your privacy will be protected in this new ecosystem.
            </p>

            <div className="bg-[var(--color-light)] border-l-4 border-[var(--color-primary)] p-8 my-12 animate-fade-up">
              <p className="text-[var(--color-ink)] italic text-2xl font-cormorant font-light leading-relaxed">
                "The intersection of AI and healthcare privacy isn't about choosing between innovation and protection—it's about ensuring both advance together."
              </p>
            </div>

            <h2 className="font-cormorant text-4xl text-[var(--color-ink)] mt-16 mb-6 font-light">
              Where HIPAA Falls Short in the AI Era
            </h2>

            <p className="mb-6">
              HIPAA established critical protections for patient health information, requiring healthcare providers, insurers, and their business associates to safeguard medical records and personal health data. However, the law was created nearly three decades ago, long before AI, machine learning, and big data analytics became integral to healthcare.
            </p>

            <p className="mb-6">
              Today's challenges extend beyond traditional HIPAA coverage. Consumer health apps that track your sleep, fitness, or mental wellness often aren't covered by HIPAA because they're not provided by healthcare entities. AI companies that purchase de-identified health data for research may technically comply with HIPAA while still raising privacy concerns. Once your data is "de-identified" and leaves the protected healthcare environment, it enters a regulatory gray area where HIPAA protections no longer apply.
            </p>

            <p className="mb-8">
              Additionally, AI systems can sometimes re-identify supposedly anonymous data by cross-referencing it with other information sources—a capability that didn't exist when HIPAA was written. This creates a privacy paradox: your data might be legally "protected" while simultaneously being vulnerable to sophisticated analysis techniques.
            </p>

            <h2 className="font-cormorant text-4xl text-[var(--color-ink)] mt-16 mb-6 font-light">
              New Privacy Risks You Should Know About
            </h2>

            <p className="mb-6">
              Understanding modern privacy risks empowers you to make informed decisions about your healthcare data. Here are the key concerns in today's AI-driven medical landscape:
            </p>

            <div className="space-y-4 my-8">
              <div className="flex gap-4 items-start">
                <div className="flex-shrink-0 mt-1">
                  <svg className="w-6 h-6 text-[var(--color-primary)]" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                </div>
                <div>
                  <h3 className="font-semibold text-[var(--color-ink)] mb-2">Data Aggregation and Profiling</h3>
                  <p>AI systems can combine health data from multiple sources—your fitness tracker, pharmacy records, genetic tests, and social media activity—to create comprehensive profiles that reveal more than you intended to share.</p>
                </div>
              </div>

              <div className="flex gap-4 items-start">
                <div className="flex-shrink-0 mt-1">
                  <svg className="w-6 h-6 text-[var(--color-primary)]" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                </div>
                <div>
                  <h3 className="font-semibold text-[var(--color-ink)] mb-2">Algorithmic Bias and Discrimination</h3>
                  <p>AI systems trained on biased data can perpetuate healthcare disparities while simultaneously accessing your sensitive information, potentially affecting diagnosis, treatment recommendations, or insurance decisions.</p>
                </div>
              </div>

              <div className="flex gap-4 items-start">
                <div className="flex-shrink-0 mt-1">
                  <svg className="w-6 h-6 text-[var(--color-primary)]" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                </div>
                <div>
                  <h3 className="font-semibold text-[var(--color-ink)] mb-2">Third-Party Access</h3>
                  <p>Healthcare providers increasingly partner with technology companies for AI services, meaning your health data may be processed by organizations you've never directly interacted with.</p>
                </div>
              </div>

              <div className="flex gap-4 items-start">
                <div className="flex-shrink-0 mt-1">
                  <svg className="w-6 h-6 text-[var(--color-primary)]" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                </div>
                <div>
                  <h3 className="font-semibold text-[var(--color-ink)] mb-2">Predictive Privacy Violations</h3>
                  <p>AI can predict health conditions you haven't disclosed—or even developed yet—based on patterns in your data, raising questions about privacy of potential future health status.</p>
                </div>
              </div>

              <div className="flex gap-4 items-start">
                <div className="flex-shrink-0 mt-1">
                  <svg className="w-6 h-6 text-[var(--color-primary)]" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                </div>
                <div>
                  <h3 className="font-semibold text-[var(--color-ink)] mb-2">Consent Confusion</h3>
                  <p>Complex privacy policies and consent forms often fail to clearly explain how AI will use your data, leaving patients to agree to terms they don't fully understand.</p>
                </div>
              </div>
            </div>

            <h2 className="font-cormorant text-4xl text-[var(--color-ink)] mt-16 mb-6 font-light">
              Practical Steps to Protect Your Health Privacy
            </h2>

            <p className="mb-6">
              While the privacy landscape is complex, you're not powerless. Here are concrete actions you can take to better protect your health information in the age of AI:
            </p>

            <div className="bg-[var(--color-cream)] rounded-2xl p-8 my-8 animate-fade-up">
              <h3 className="font-semibold text-[var(--color-ink)] text-xl mb-4">Ask the Right Questions</h3>
              <ul className="space-y-3">
                <li className="flex gap-3">
                  <span className="text-[var(--color-primary)] font-bold">•</span>
                  <span>Does your healthcare provider use AI systems? If so, how is your data being processed and protected?</span>
                </li>
                <li className="flex gap-3">
                  <span className="text-[var(--color-primary)] font-bold">•</span>
                  <span>Are third-party companies involved in analyzing your health data?</span>
                </li>
                <li className="flex gap-3">
                  <span className="text-[var(--color-primary)] font-bold">•</span>
                  <span>What happens to your data after it's collected—is it sold, shared, or used for research?</span>
                </li>
                <li className="flex gap-3">
                  <span className="text-[var(--color-primary)] font-bold">•</span>
                  <span>Can you opt out of having your data used for AI training or other secondary purposes?</span>
                </li>
              </ul>
            </div>

            <div className="bg-[var(--color-cream)] rounded-2xl p-8 my-8 animate-fade-up">
              <h3 className="font-semibold text-[var(--color-ink)] text-xl mb-4">Review Privacy Policies Carefully</h3>
              <ul className="space-y-3">
                <li className="flex gap-3">
                  <span className="text-[var(--color-primary)] font-bold">•</span>
                  <span>Read privacy policies for health apps before downloading, focusing on data sharing and AI use sections</span>
                </li>
                <li className="flex gap-3">
                  <span className="text-[var(--color-primary)] font-bold">•</span>
                  <span>Look for clear explanations of how your data will be de-identified and who has access</span>
                </li>
                <li className="flex gap-3">
                  <span className="text-[var(--color-primary)] font-bold">•</span>
                  <span>Check whether the app or service is HIPAA-compliant if it handles health information</span>
                </li>
              </ul>
            </div>

            <div className="bg-[var(--color-cream)] rounded-2xl p-8 my-8 animate-fade-up">
              <h3 className="font-semibold text-[var(--color-ink)] text-xl mb-4">Exercise Your Rights</h3>
              <ul className="space-y-3">
                <li className="flex gap-3">
                  <span className="text-[var(--color-primary)] font-bold">•</span>
                  <span>Request access to your health records to see what information is being stored</span>
                </li>
                <li className="flex gap-3">
                  <span className="text-[var(--color-primary)] font-bold">•</span>
                  <span>Ask for corrections if you find inaccurate information</span>
                </li>
                <li className="flex gap-3">
                  <span className="text-[var(--color-primary)] font-bold">•</span>
                  <span>Request an accounting of disclosures to learn who has accessed your records</span>
                </li>
                <li className="flex gap-3">
                  <span className="text-[var(--color-primary)] font-bold">•</span>
                  <span>Submit written objections to uses of your data that make you uncomfortable</span>
                </li>
              </ul>
            </div>

            <div className="bg-[var(--color-cream)] rounded-2xl p-8 my-8 animate-fade-up">
              <h3 className="font-semibold text-[var(--color-ink)] text-xl mb-4">Be Selective About Health Apps</h3>
              <ul className="space-y-3">
                <li className="flex gap-3">
                  <span className="text-[var(--color-primary)] font-bold">•</span>
                  <span>Prioritize apps from established healthcare organizations or those certified by reputable privacy organizations</span>
                </li>
                <li className="flex gap-3">
                  <span className="text-[var(--color-primary)] font-bold">•</span>
                  <span>Limit permissions—don't give health apps access to contacts, location, or other data they don't need</span>
                </li>
                <li className="flex gap-3">
                  <span className="text-[var(--color-primary)] font-bold">•</span>
                  <span>Consider whether you truly need an app to track certain health metrics</span>
                </li>
                <li className="flex gap-3">
                  <span className="text-[var(--color-primary)] font-bold">•</span>
                  <span>Delete apps you're no longer using and request deletion of your data</span>
                </li>
              </ul>
            </div>

            <h2 className="font-cormorant text-4xl text-[var(--color-ink)] mt-16 mb-6 font-light">
              The Future of Healthcare Privacy
            </h2>

            <p className="mb-6">
              Privacy protections are evolving to meet the challenges of AI-driven healthcare. Some states have enacted stronger health privacy laws that go beyond HIPAA. The European Union's General Data Protection Regulation (GDPR) provides more comprehensive protections that are influencing global standards. Healthcare organizations are developing AI ethics frameworks that prioritize privacy and transparency.
            </p>

            <p className="mb-6">
              However, meaningful protection requires ongoing vigilance from patients, providers, policymakers, and technology developers. The goal isn't to reject AI in healthcare—the potential benefits are too significant—but rather to ensure that innovation doesn't come at the cost of patient privacy and autonomy.
            </p>

            <p className="mb-8">
              As a patient, you have the right to understand how your health information is being used and to advocate for stronger protections. Staying informed about these issues, asking questions, and making conscious choices about your health data are essential steps in protecting your privacy in this new era of healthcare.
            </p>

            <h2 className="font-cormorant text-4xl text-[var(--color-ink)] mt-16 mb-6 font-light">
              Moving Forward with Confidence
            </h2>

            <p className="mb-6">
              The intersection of AI and healthcare privacy is complex, but you don't have to navigate it alone. Healthcare providers who prioritize transparency, respect patient autonomy, and implement robust privacy protections are leading the way toward a future where innovation and privacy coexist.
            </p>

            <p className="mb-6">
              If you have concerns about how your health information is being handled or questions about AI use in your care, don't hesitate to speak up. Healthcare providers should welcome these conversations and work with you to address your concerns.
            </p>

            <p className="text-lg font-medium">
              At Try MedReception, we believe that every patient deserves to understand how their health information is protected and used. If you're looking for care from providers who prioritize both innovative treatment and rigorous privacy protection, we're here to help you find the right fit for your needs.
            </p>
          </div>
        </div>

        <div className="bg-[var(--color-cream)] rounded-2xl p-8 max-w-3xl mx-auto my-16 px-6 animate-fade-up">
          <div className="flex gap-6 items-start">
            <div className="flex-shrink-0">
              <div className="bg-[var(--color-light)] rounded-full w-16 h-16 flex items-center justify-center">
                <svg className="w-8 h-8 text-[var(--color-primary)]" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
                </svg>
              </div>
            </div>
            <div>
              <h3 className="font-semibold text-[var(--color-ink)] text-lg mb-2">Written by the Try MedReception Clinical Team</h3>
              <p className="text-[var(--color-muted)] text-sm leading-relaxed">
                Board-certified providers specializing in Other Medical, dedicated to delivering evidence-based patient education and compassionate care guidance.
              </p>
            </div>
          </div>
        </div>
      </article>

      <section className="bg-[var(--color-cream)] py-16">
        <div className="max-w-7xl mx-auto px-6">
          <h3 className="font-cormorant text-4xl text-[var(--color-ink)] mb-12 text-center font-light">
            Related Resources
          </h3>
          
          <div className="grid md:grid-cols-3 gap-8">
            <a href="/blog" className="group bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-xl transition-all duration-300 animate-fade-up">
              <div className="bg-gradient-to-br from-[var(--color-light)] to-[var(--color-cream)] h-48 flex items-center justify-center">
                <svg className="w-16 h-16 text-[var(--color-primary)] opacity-50" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z" />
                </svg>
              </div>
              <div className="p-6">
                <div className="text-xs uppercase tracking-wider text-[var(--color-primary)] mb-2 font-medium">
                  Patient Rights
                </div>
                <h4 className="font-cormorant text-2xl text-[var(--color-ink)] mb-3 group-hover:text-[var(--color-primary)] transition-colors">
                  Understanding Your HIPAA Rights: A Patient's Guide
                </h4>
                <p className="text-[var(--color-muted)] text-sm leading-relaxed mb-4">
                  Learn about your fundamental rights under HIPAA and how to exercise them in your healthcare journey.
                </p>
                <div className="text-[var(--color-primary)] text-sm font-medium flex items-center gap-2">
                  Read More
                  <svg className="w-4 h-4 group-hover:translate-x-1 transition-transform" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
                  </svg>
                </div>
              </div>
            </a>

            <a href="/blog" className="group bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-xl transition-all duration-300 animate-fade-up">
              <div className="bg-gradient-to-br from-[var(--color-light)] to-[var(--color-cream)] h-48 flex items-center justify-center">
                <svg className="w-16 h-16 text-[var(--color-primary)] opacity-50" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M10.5 1.5H8.25A2.25 2.25 0 006 3.75v16.5a2.25 2.25 0 002.25 2.25h7.5A2.25 2.25 0 0018 20.25V3.75a2.25 2.25 0 00-2.25-2.25H13.5m-3 0V3h3V1.5m-3 0h3m-3 18.75h3" />
                </svg>
              </div>
              <div className="p-6">
                <div className="text-xs uppercase tracking-wider text-[var(--color-primary)] mb-2 font-medium">
                  Digital Health
                </div>
                <h4 className="font-cormorant text-2xl text-[var(--color-ink)] mb-3 group-hover:text-[var(--color-primary)] transition-colors">
                  Choosing Safe Health Apps: What to Look For
                </h4>
                <p className="text-[var(--color-muted)] text-sm leading-relaxed mb-4">
                  Essential criteria for evaluating the privacy and security of health and wellness applications.
                </p>
                <div className="text-[var(--color-primary)] text-sm font-medium flex items-center gap-2">
                  Read More
                  <svg className="w-4 h-4 group-hover:translate-x-1 transition-transform" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
                  </svg>
                </div>
              </div>
            </a>

            <a href="/blog" className="group bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-xl transition-all duration-300 animate-fade-up">
              <div className="bg-gradient-to-br from-[var(--color-light)] to-[var(--color-cream)] h-48 flex items-center justify-center">
                <svg className="w-16 h-16 text-[var(--color-primary)] opacity-50" fill="none" stroke="currentColor" strokeWidth={1.5} viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M9.879 7.519c1.171-1.025 3.071-1.025 4.242 0 1.172 1.025 1.172 2.687 0 3.712-.203.179-.43.326-.67.442-.745.361-1.45.999-1.45 1.827v.75M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9 5.25h.008v.008H12v-.008z" />
                </svg>
              </div>
              <div className="p-6">
                <div className="text-xs uppercase tracking-wider text-[var(--color-primary)] mb-2 font-medium">
                  Healthcare Technology
                </div>
                <h4 className="font-cormorant text-2xl text-[var(--color-ink)] mb-3 group-hover:text-[var(--color-primary)] transition-colors">
                  Questions to Ask About AI in Your Healthcare
                </h4>
                <p className="text-[var(--color-muted)] text-sm leading-relaxed mb-4">
                  Empower yourself with the right questions when your healthcare provider uses artificial intelligence.
                </p>
                <div className="text-[var(--color-primary)] text-sm font-medium flex items-center gap-2">
                  Read More
                  <svg className="w-4 h-4 group-hover:translate-x-1 transition-transform" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
                  </svg>
                </div>
              </div>
            </a>
          </div>
        </div>
      </section>

      <section className="bg-gradient-to-br from-[var(--color-dark)] to-[var(--color-primary)] py-20 text-white text-center">
        <div className="max-w-4xl mx-auto px-6">
          <h2 className="font-cormorant text-5xl font-light mb-6 animate-fade-up">
            Ready to Take the Next Step?
          </h2>
          <p className="text-xl mb-8 text-white/90 animate-fade-up">
            Our team is here to help.
          </p>
          <a 
            href="/contact" 
            className="inline-block bg-white text-[var(--color-primary)] px-8 py-4 rounded-full font-medium hover:bg-[var(--color-cream)] transition-all duration-300 hover:scale-105 hover:shadow-xl animate-fade-up"
          >
            Get in Touch
          </a>
        </div>
      </section>
    </main>
  )
}